version: "1"
projects:
  - name: maresia-grill
    environments:
      - name: production
        envVarGroups:
          - name: production
        services:
          - type: web
            name: pwa
            runtime: static
            buildCommand: npm install && npm run build
            staticPublishPath: dist
            routes:
              - type: rewrite
                source: /s/*
                destination: /index.html
              - type: rewrite
                source: /*
                destination: /index.html
            envVars:
              - fromGroup: production
      - name: staging
        envVarGroups:
          - name: staging
        services:
          - type: web
            name: pwa
            runtime: static
            buildCommand: npm install && npm run build
            staticPublishPath: dist
            previews:
              generation: automatic
            routes:
              - type: rewrite
                source: /s/*
                destination: /index.html
              - type: rewrite
                source: /*
                destination: /index.html
            envVars:
              - fromGroup: staging
