version: "1"
projects:
  - name: maresia-grill
    environments:
      - name: production
        envVarGroups:
          - name: production
        services:
          - type: web
            name: web-production
            branch: main
            runtime: static
            rootDir: .
            buildCommand: corepack enable && corepack prepare pnpm@9.0.0 --activate && pnpm install --frozen-lockfile && pnpm --filter @maresia-grill/web build
            staticPublishPath: apps/web/dist
            domains:
              - maresiagrill.com
            routes:
              - type: rewrite
                source: /s/*
                destination: /index.html
              - type: rewrite
                source: /*
                destination: /index.html
            envVars:
              - fromGroup: production
      - name: staging
        envVarGroups:
          - name: staging
        services:
          - type: web
            name: web-staging
            branch: staging
            runtime: static
            rootDir: .
            buildCommand: corepack enable && corepack prepare pnpm@9.0.0 --activate && pnpm install --frozen-lockfile && pnpm --filter @maresia-grill/web build
            staticPublishPath: apps/web/dist
            routes:
              - type: rewrite
                source: /s/*
                destination: /index.html
              - type: rewrite
                source: /*
                destination: /index.html
            envVars:
              - fromGroup: staging
